version: '3.8'

services:
  db:
    image: postgres:15
    container_name: balance_app_db
    environment:
      POSTGRES_USER: balance_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: balance_app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
