version: '3.8'

services:
  db:
    image: postgres:15
    container_name: balance_app_db
    environment:
      POSTGRES_USER: balance_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: balance_app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
